<?php include_once '../../../private/initialize.php'; ?>

<?php include SHARED_PATH. "/administrator_header.php"; ?>

<div id="main">
	<div class = "slide-wrap">
			<ul id = "banner-nav">
				<li><img src="<?php echo url_for("/img/banner.jpg") ?>" id = "imgFade"></li>
			</ul>
		</section>
		<div class = "clearfix"></div>
		<div id = "inner-wraper">
		<section class = "one-third">
			<div class = "circle">
				<td><i class = "fa fa-users"><img src=""></i></td>
			</div>
			<h5>Schedule</h5>
			<p>this is sample design.</p>
		</section>
		<section class = "one-third">
			<div class = "circle">
				<td><i class = "fa fa-map-marker"><img src=""></i></td>
			</div>
			<h5>Convenient Location</h5>
			<p>this is sample design.</p>
		</section>
		<section class = "one-third">
			<div class = "circle">
				<td><i class = "fa fa-cgeck-square-o"><img src=""></i></td>
			</div>
			<h5>Ckeck Up Location</h5>
			<p>this is sample design.</p>
		</section>
		<!--End Horizontal-->
		<div class = "clearfix"></div>
			<article>
				<img src="<?php echo url_for("/img/one.jpg") ?>">
			</article>
			<aside>
				<h5>Our Facility</h5>
					<br>
					<ul>
					<li><h5>Wifi Connection</h5></li>
					<li><h5>Member music Request</h5></li>
					<li><h5>Open 24 Hours / 7 days a week</h5></li>
					<li><h5>cardio machine theater</h5></li>
				</ul>
			</aside>
		<div class = "clearfix"></div>
			<section class = "one-third">
				<h5>Barangay League</h5>
				<img src="<?php echo url_for("/img/two.jpg") ?>">
				<p>Akin ka nalang. for your own sake. hahaha!!!! this is sample design.Test!asdasdasdsa</p>
			</section>
			<section class = "one-third">
				<h5>Sinakulo</h5>
				<img src="<?php echo url_for("/img/three.jpg") ?>">
				<p>Akin ka nalang. for your own sake. hahaha!!!! this is sample design.Test!sadadasdsa</p>
			</section>
			<section class = "one-third">
				<h5>Festival</h5>
				<img src="<?php echo url_for("/img/four.jpg") ?>">
				<p>Akin ka nalang. for your own sake. hahaha!!!! this is sample design.Test!asdasdassad</p>
			</section>
	</div>
</div>











<?php include SHARED_PATH.'/administrator_footer.php'; ?>