<?php include_once '../../private/initialize.php'; ?>

<?php include SHARED_PATH. "/administrator_header.php"; ?>

<div id="main">
	<div class = "clearfix"></div>
 	<div id = "inner-wraper">
 		<section class = "one-second">
				<td><img src="<?php echo url_for("/img/eight.jpg") ?>"></td>
			<h5> Barangay Captain</h5>
		</section>
		<section class = "one-second">
			<td><img src="<?php echo url_for("/img/eight.jpg") ?>"></td>
			<h5>Vice - Captain</h5>
		</section>
		<div class = "clearfix"></div>
		<section class = "one-fourth">
			<td><img src="<?php echo url_for("/img/eight.jpg") ?>"></td>
			<h5>Konsehal</h5>
		</section>
		<section class = "one-fourth">
			<td><img src="<?php echo url_for("/img/eight.jpg") ?>"></td>
			<h5>Konsehal</h5>
		</section>
		<section class = "one-fourth">
			<td><img src="<?php echo url_for("/img/eight.jpg") ?>"></td>
			<h5>Konsehal</h5>
		</section>
		<div class = "clearfix"></div>
		<section class = "one-fourth">
			<td><img src="<?php echo url_for("/img/eight.jpg") ?>"></td>
			<h5>Konsehal</h5>
		</section>
		<section class = "one-fourth">
			<td><img src="<?php echo url_for("/img/eight.jpg") ?>"></td>
			<h5>Konsehal</h5>
		</section>
		<section class = "one-fourth">
			<td><img src="<?php echo url_for("/img/eight.jpg") ?>"></td>
			<h5>Konsehal</h5>
		</section>
	</div>
</div>













<?php include SHARED_PATH.'/administrator_footer.php'; ?>